spring.datasource.driver-class-name=tech.ydb.jdbc.YdbDriver
spring.datasource.url=jdbc:ydb:grpcs://ydb.serverless.yandexcloud.net:2135/ru-central1/b1gd88cauv7oml0bhra0/etndmtgov7vfcicu7ev5?saKeyFile=authorized_key.json
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

